import PushNotification from 'react-native-push-notification';
import moment from 'moment';
PushNotification.configure({
  onNotification: notification => {
    console.log('LOCAL NOTIFICATION=> ', notification);
  },
  popInitialNotification: true,
  requestPermissions: true,
});

export const LocalNotification = () => {
  PushNotification.localNotification({
    /* Android Only Properties */
    //id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
    //ticker: "My Notification Ticker", // (optional)
    autoCancel: true, // (optional) default: true
    largeIcon: 'healthearnlogo', // (optional) default: "ic_launcher"
    smallIcon: 'healthearnlogo', // (optional) default: "ic_notification" with fallback for "ic_launcher"
    //bigText: 'what are you', // (optional) default: "message" prop
    //subText: '', // (optional) default: none
    //color: 'red', // (optional) default: system default
    vibrate: true, // (optional) default: true
    vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
    //tag: 'some_tag', // (optional) add tag to message
    //group: 'group', // (optional) add group to message
    //ongoing: false, // (optional) set whether this is an "ongoing" notification
    //priority: 'high', // (optional) set notification priority, default: high
    //visibility: 'private', // (optional) set notification visibility, default: private
    //importance: 'high', // (optional) set notification importance, default: high

    /* iOS and Android properties */
    title: 'Time for some Data sending', // (optional)
    message: 'Please send your data to tangle', // (required)
    playSound: true, // (optional) default: true
    soundName: 'android.resource://com.healthearn/raw/mysound.mp3', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
    //number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
    //repeatType: 'time', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
    //repeatTime: 60000,
    //actions: '["Yes", "No"]', // (Android only) See the doc for notification actions to know more
  });
};

export const LocalNotificationSchedule = () => {
  PushNotification.localNotificationSchedule({
    date: new Date(
      moment()
        .startOf('date')
        .valueOf() +
        86400 * 1000,
    ),
    /* Android Only Properties */
    //id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
    //ticker: "My Notification Ticker", // (optional)
    autoCancel: true, // (optional) default: true
    largeIcon: 'healthearnlogo', // (optional) default: "ic_launcher"
    smallIcon: 'healthearnlogo', // (optional) default: "ic_notification" with fallback for "ic_launcher"
    //bigText: 'what are you', // (optional) default: "message" prop
    //subText: '', // (optional) default: none
    //color: 'red', // (optional) default: system default
    vibrate: true, // (optional) default: true
    vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
    //tag: 'some_tag', // (optional) add tag to message
    //group: 'group', // (optional) add group to message
    //ongoing: false, // (optional) set whether this is an "ongoing" notification
    //priority: 'high', // (optional) set notification priority, default: high
    //visibility: 'private', // (optional) set notification visibility, default: private
    //importance: 'high', // (optional) set notification importance, default: high

    /* iOS and Android properties */
    title: 'Time for some Data sending', // (optional)
    message: 'Please send your data to tangle', // (required)
    playSound: true, // (optional) default: true
    soundName: 'android.resource://com.healthearn/raw/mysound.mp3', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
    //number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
    //repeatType: 'minute', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
    //actions: '["Yes", "No"]', // (Android only) See the doc for notification actions to know more
  });
};
